// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNoMVnujr-_dxbJrHyd-6JXLnZ8kP4J0',
    appId: '1:199064377680:web:d96868f1f94120b602f455',
    messagingSenderId: '199064377680',
    projectId: 'church-reimbursment',
    authDomain: 'church-reimbursment.firebaseapp.com',
    storageBucket: 'church-reimbursment.firebasestorage.app',
    measurementId: 'G-VSFZ418NXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFfhgPiTyQ_vw4e51NxbyNNpiYq-_1u-M',
    appId: '1:199064377680:android:71c532ba92ef454e02f455',
    messagingSenderId: '199064377680',
    projectId: 'church-reimbursment',
    storageBucket: 'church-reimbursment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzU7gZLsw0bpoxnNo8iKKQW4scuViXu6k',
    appId: '1:199064377680:ios:3d29ae0d00f3795102f455',
    messagingSenderId: '199064377680',
    projectId: 'church-reimbursment',
    storageBucket: 'church-reimbursment.firebasestorage.app',
    iosBundleId: 'com.example.churchReimbursement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzU7gZLsw0bpoxnNo8iKKQW4scuViXu6k',
    appId: '1:199064377680:ios:3d29ae0d00f3795102f455',
    messagingSenderId: '199064377680',
    projectId: 'church-reimbursment',
    storageBucket: 'church-reimbursment.firebasestorage.app',
    iosBundleId: 'com.example.churchReimbursement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdNoMVnujr-_dxbJrHyd-6JXLnZ8kP4J0',
    appId: '1:199064377680:web:824742324ab4b58902f455',
    messagingSenderId: '199064377680',
    projectId: 'church-reimbursment',
    authDomain: 'church-reimbursment.firebaseapp.com',
    storageBucket: 'church-reimbursment.firebasestorage.app',
    measurementId: 'G-RG7TG0KNYV',
  );
}
